### ISSUE TITLE
How to set two different pickers in the same template

### ISSUE THREAD

**Issue by Zanoth** [evansmwendwa/ng2-daterangepicker#20]
Hey there! Firstly I want to thank you for your amazing work, it has been doing a sweet work so far and it's really simple to use, and of course, the style is gorgeous.

As for my issue, I want to clarify i'm a total beginner on angular 2 and frontend develop. I want to use two different pickers in one template. One is for estimates, and the other one is for departure and return dates. 
A Single Picker, and a Range Picker, in other words.
I wanted to override the automatic loading dates of the pickers with this code.
```
this.picker.datePicker.setStartDate(new Date(this.Estimate.DepartureDate));
 this.picker.datePicker.setEndDate(new Date(this.Estimate.ReturnDate));
```

which loads in ngAfterView, but it is changing the single picker date, not the RangePicker. 

Just in case, I copied this code of yours to declare picker:
```
 @ViewChild(DaterangePickerComponent)
    private picker: DaterangePickerComponent;
```
I was reading the docs and the code, but sadly I couldn't find an answer, thank you!

**Comment by evansmwendwa** [comment]
@Zanoth have you tried binding to options?

There a lot's of available options including the default start and ending date. The Demo has a good example that uses multiple calendars in the same page https://embed.plnkr.co/94HAl4q2ITLnahjhYOY0/ 

Try creating an options object that you can initialize with pure dates using something like moment js

``` javascript
public options = {
  start: moment().subtract(12, 'month'),
  end: moment().subtract(6, 'month')
}

then in your template
<input type="text" daterangepicker [options]="options" />
```

If you must use the methods instead of setting default options substitute ` @ViewChild` with ` @ViewChildren` when using multiple pickers. See Angular's documentation on that https://angular.io/docs/ts/latest/api/core/index/ViewChildren-decorator.html

Also the original project has full documentation on all available options, methods and events http://www.daterangepicker.com/

If you are still having problems create a plunkr (you can fork the demo one) and I can help you with a real working example.
