### ISSUE TITLE
build issue

### ISSUE THREAD

**Issue by ahsan9797** [evansmwendwa/ng2-daterangepicker#91]
Hi,

I used the same imports as you provided in systemjs file and rest also same as you provided but while build my application getting error as below : ENOENT: no such file or directory, open 'F:\IdeaProjects\GCU_Project\GCU_Code_Base\sprint94\gcu-sis.sisweb\ng2-daterangepicker'?[39m
 
I am using grunt build.
below are imports I added in system js : 
'ng2-daterangepicker':          'npm:ng2-daterangepicker',
'jquery':                       'npm:jquery/dist/jquery.js',
'moment':                       'npm:moment',
'bootstrap-daterangepicker':    'npm:bootstrap-daterangepicker/daterangepicker.js'

**Comment by evansmwendwa** [comment]
I don't have good experience with either system js or grunt to assist you with this other than the provided setup for System JS. I do concentrate on testing in Angular CLI which is the default supported way of building angular apps. 

If you find a solution it would be good to post it so that you can assist others with the same issue.
